# ddve configuration
ddve:
  host: '192.168.41.52'
  username: 'sysadmin'
  password: 'sdcTeam21'
  rest_port: '3009'

# database configuration
database:
  host: 'localhost'
  port: '3306'
  username: 'root'
  password: 'sdcTeam21!'
  name: 'readop_development'

debug:
  database_engine_echo: False
